### ISSUE TITLE
Cannot open template (absolute path)

### ISSUE THREAD

**Issue by ncarboni** [chin-rcip/CRITERIA#11]
Hello, 
I have the problem calling the script from outside its folder:
`python3 /Users/nicola/Downloads/CRITERIA-master/criteria.py ontology Person_Actor_Relations.ttl Person_Actor_Relations.mmd`

I received the following errors

```
Traceback (most recent call last):
  File "/Users/nicola/Downloads/CRITERIA-master/criteria.py", line 268, in <module>
    main(args.Type, args.rdf, args.mmd)
  File "/Users/nicola/Downloads/CRITERIA-master/criteria.py", line 252, in main
    ontology(rdf, mmd)
  File "/Users/nicola/Downloads/CRITERIA-master/criteria.py", line 201, in ontology
    template = open("./src/templates/ontology.mmd", "r", encoding="utf-8")
```
The error seems to be connected with the possibility to load the template ontology in ` ./src/templates/ontology.mmd`
If I move the corresponding file in the folder where I want to launch the script, everything works. 
It is not critical, but I wanted to report the issue :-)

**Comment by TrangDg** [comment]
Hi Nicola, thank you for raising the issue.
You are right that all files paths that hardcoded in the script are relative to the script folders. It's simply a script and not a full-scale package module so it's unfortunately limited. 
So there are two options:
1. move the whole Criteria folder to where you want to launch the script
2. use full path for your input (rdf) and output (mmd) so you can call them from wherever you launch the script.

I hope that helps.

**Comment by ncarboni** [comment]
Thanks, I just moved the src/ folder and it works perfectly :-)
