### ISSUE TITLE
Update Base Ontologies

### ISSUE THREAD

**Issue by Habennin** [chin-rcip/CRITERIA#15]
Just wondering if now that CRM 7.1.1 stable is out, if it wouldn't be good to upgrade to this. And also consider what other RDFS of CRM family should be in the base package?

**Comment by chin-rcip** [comment]
@Habennin,
I can replace the current CRM v6.2.1. with the stable RDF in the next iteration. Other RDFS of CRM family in current base package include:
- CRMdig_v3.2.2.rdfs
- CRMpc_v1.1.1.rdfs
- FRBR2.4-draft.rdfs

I am planning to add:
- CRMarcheo_v1.4.1
- CRMsci_v1.2.6

On the same note, I am also planning to add flexibility allowing user to configure their own ontology, and possibly styling.

**Comment by chin-rcip** [comment]
@Habennin I have update the master branch with the changes as described in my previous comment.
