### ISSUE TITLE
External input/output folders

### ISSUE THREAD

**Issue by illip** [chin-rcip/CRITERIA#2]
Currently, it is impossible to use other local folders for the inputs and/or the outputs than the ones provided by the script. Eventually, it would be great to offer the option to the user to select the folder(s) he/she prefers to avoid duplication of the data.

**Comment by ncarboni** [comment]
Also, linked with it, specify as input a folder and not a single file.

**Comment by TrangDg** [comment]
@ncarboni, by "**input a folder**", did you mean the script should be able to process all the files in the folder with a single command? 
I think in that case, we need another script that calls `criteria.py` to run each file.

**Comment by ncarboni** [comment]
> @ncarboni, by "**input a folder**", did you mean the script should be able to process all the files in the folder with a single command?

yes, I meant that. However, once it is possible to set as input a file in external folder, it is indeed true that we can easily use batch to call criteria.py foe each *.ttl file we want

**Comment by TrangDg** [comment]
User can now provide their own path to input/output files for the arguments.
If the files locate in a different directory than CRITERIA, need to provide the full path to the file, e.g. **`/User/your_username/your_project/folder/input/input.ttl`.**
