### ISSUE TITLE
Develop an Online Live Editor

### ISSUE THREAD

**Issue by illip** [chin-rcip/CRITERIA#3]
At some point, it would be interesting to develop an Online Live Editor something like the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/) but with an RDF serialization as input.

A good [example](https://research.ng-london.org.uk/modelling/) to look at.

**Comment by TrangDg** [comment]
The live editor is now available here: http://chinrcip.pythonanywhere.com/
