### ISSUE TITLE
Manage other input formats

### ISSUE THREAD

**Issue by illip** [chin-rcip/CRITERIA#4]
For the moment we parse .ttl files only, however, rdflib can process other formats that we should also include as valid inputs.

> Parsers & Serializers
> * for RDF/XML, N3, NTriples, N-Quads, Turtle, TriX, RDFa and Microdata
> * and JSON-LD, via a plugin module

JSON-LD should be our next available format since many cultural projects use it.

**Comment by TrangDg** [comment]
Users can now use other linked data format as input, including `JSON-LD`. Users need to install [rdflib-jsonld](https://github.com/RDFLib/rdflib-jsonld) plugin.
